import os

import mistune


EPISODE_NOTES_DIR = 'episode_notes'


def main():
    with open('episode_header.tmpl') as header:
        header_contents = header.read()
    with open('episode_footer.tmpl') as footer:
        footer_contents = footer.read()

    for filename in os.listdir(EPISODE_NOTES_DIR):
        base, ext = os.path.splitext(filename)
        if ext != 'md':
            continue

        with open(os.path.join(EPISODE_NOTES_DIR, filename)) as f:
            lines = f.readlines()
            lines = lines[1:]   # Slice off the title.
            contents = ''.join(lines)
        guts = mistune.html(contents)

        with open(base + '.html', 'w') as file:
            file.write("<!-- DO NOT EDIT -- episode notes autogenerated by TLBHit's render.py -->\n")
            file.write(header_contents)
            file.write(guts)
            file.write(footer_contents)


if __name__ == '__main__':
    main()
